version: '3'
services:
  web:
    build: .
    tty: true
    stdin_open: true
    container_name: flask_mvc
    volumes:
      - ../workspace:/workspace
    ports:
      - 127.0.0.1:8080:1323
      - 127.0.0.1:9000:9000
